# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths: 
    - '**'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: job1
      run: echo "job1"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: github.ref != 'master'
    steps:
    - name: job2
      run: echo "job2"
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
    - name: job3
      run: echo "job3"
  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
    - name: job4
      run: echo "job4"
  job5:
    runs-on: ubuntu-latest
    needs: job4
    steps:
    - name: job5
      run: echo "job5"

